name: app
channels:
  - conda-forge
dependencies:
  - python=3.10
  - opencv
  - pillow
  - numpy
  - scikit-learn
  - pip
  - pip:
      - streamlit
      - tensorflow
      - tf-keras
      - deepface
      - retina-face
      - gdown
      - pandas
      - tqdm
      - gunicorn
      - Flask
      - mtcnn
