name: app
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - opencv
  - pillow
  - numpy
  - pandas
  - scikit-learn
  - tqdm
  - flask
  - pip
  - pip:
      - streamlit
      - tensorflow>=2.13.0
      - tf-keras>=2.13.0
      - deepface
      - retina-face
      - gdown
      - mtcnn
